version: "3.9"

services:
  backend:
    build:
      context: .
    stdin_open: true
    ports:
      - 8000:8000
    volumes:
      - ./algebraic_predictor:/algebraic_predictor
    command: sh -c "python manage.py wait_for_db &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    environment:
      - REDIS_LOCATION=redis://redis:6379/1
    depends_on:
      - db
      - redis

  beat:
    build:
      context: .
    stdin_open: true
    env_file:
      - .env
    environment:
      - REDIS_LOCATION=redis://redis:6379/1
    volumes:
      - ./algebraic_predictor:/algebraic_predictor
    command: celery -A backend beat -l info
    depends_on:
      - db
      - redis

  worker:
    build:
      context: .
    stdin_open: true
    env_file:
      - .env
    environment:
      - REDIS_LOCATION=redis://redis:6379/1
    volumes:
      - ./algebraic_predictor:/algebraic_predictor
    command: celery -A backend worker -l info
    depends_on:
      - db
      - redis

  db:
    image: postgres:14-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data/
    env_file:
      - .env

  redis:
    image: redis:bullseye
    ports:
      - "6397:6397"

volumes:
  dev-db-data:
